// <auto-generated />
using System;
using Kdbndp.EntityFrameworkCore.KingbaseES.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace kingbasetest.Migrations
{
    [DbContext(typeof(Modules))]
    partial class ModulesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            KdbndpModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog_Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int?>("Ager")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Birthy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Ids")
                        .HasColumnType("uuid");

                    b.Property<float?>("Moneies")
                        .HasColumnType("real");

                    b.Property<float>("Money")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Pi")
                        .HasColumnType("double precision");

                    b.Property<double?>("Pis")
                        .HasColumnType("double precision");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<bool>("Sex")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Sexy")
                        .HasColumnType("boolean");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("States")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Kdb_Blog_Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
